Create Schema "RoyalReads_DB";
Set SEARCH_PATH to "RoyalReads_DB", public;


CREATE TABLE Category
(
	CategoryID INTEGER PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	CategoryType VARCHAR(20) NOT NULL
);

CREATE TABLE SalesRep
(
	SalesRepID INTEGER PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE Shop
(
	ShopID INTEGER PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE Publisher
(
	PublisherID INTEGER PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE Book
(
	BookID INTEGER PRIMARY KEY,
	Title VARCHAR(50) NOT NULL,
	Price DECIMAL(10,2) NOT NULL,
	CategoryID INTEGER NOT NULL,
	PublisherID INTEGER NOT NULL,
    FOREIGN KEY (CategoryID) REFERENCES Category (CategoryID) ON DELETE CASCADE,
    FOREIGN KEY (PublisherID) REFERENCES Publisher (PublisherID) ON DELETE CASCADE
);

CREATE TABLE ShopOrder
(
	ShopOrderID INTEGER PRIMARY KEY,
	OrderDate DATE NOT NULL,
	ShopID INTEGER NOT NULL,
	SalesRepID INTEGER NOT NULL,
	Status VARCHAR(20) NOT NULL,
    FOREIGN KEY (ShopID) REFERENCES Shop (ShopID),
    FOREIGN KEY (SalesRepID) REFERENCES SalesRep(SalesRepID) ON DELETE CASCADE
);

CREATE TABLE Orderline
(
	ShopOrderID INTEGER, -- Foreign primary key
	BookID INTEGER NOT NULL,
	Quantity INTEGER NOT NULL,
	UnitSellingPrice DECIMAL (10,2) NOT NULL
    FOREIGN KEY (ShopOrderID) REFERENCES ShopOrder(ShopOrderID) ON DELETE CASCADE,
    FOREIGN KEY (BookID) REFERENCES Book (BookID) ON DELETE CASCADE
);			

